name       : haskell-regex-compat
version    : 0.95.2.0
release    : 5
source     :
    - https://hackage.haskell.org/package/regex-compat-0.95.2.0/regex-compat-0.95.2.0.tar.gz : 1fc90e476fc30ced2404fac04433ec422463210a32b49f739864e1ebf2278406
license    : BSD-3-Clause
component  : programming.haskell
summary    : One module layer over regex-posix to replace Text.Regex
description: |
    One module layer over regex-posix to replace Text.Regex
builddeps  :
    - haskell-cabal-install
    - haskell-regex-posix-devel
rundeps    :
    - devel:
        - haskell-regex-posix-devel
networking : yes
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
