name       : haskell-regex-compat
version    : 0.95.1
release    : 1
source     :
    - http://hackage.haskell.org/package/regex-compat-0.95.1/regex-compat-0.95.1.tar.gz : d57cb1a5a4d66753b18eaa37a1621246f660472243b001894f970037548d953b
license    : BSD-3-Clause
component  : programming
summary    : One module layer over regex-posix to replace Text.Regex
description: |
    One module layer over regex-posix to replace Text.Regex
builddeps  :
    - ghc
    - haskell-regex-posix
setup      : |
    sudo ghc-pkg recache
    ghc -threaded --make Setup
    ./Setup configure --enable-shared \
                      --prefix=/usr \
                      --docdir="/usr/share/doc/\$compiler/\$pkgid" \
                      --libdir=/usr/lib64 \
                      --libsubdir="\$compiler/\$pkgid" \
                      --datadir=/usr/share \
                      --sysconfdir=/etc
build      : |
    ./Setup build
install    : |
    export GHCV=`readlink /usr/bin/ghc`
    ./Setup copy --destdir=$installdir
    ./Setup register --gen-pkg-config
    install -D -m 00644 regex-compat-$version.conf $installdir/usr/lib64/$GHCV/package.conf.d/regex-compat-$version.conf
    rm -f $installdir/usr/lib64/$GHCV/regex-compat-$version/*.a
