name       : haskell-regex-compat
version    : 0.95.1
release    : 2
source     :
    - http://hackage.haskell.org/package/regex-compat-0.95.1/regex-compat-0.95.1.tar.gz : d57cb1a5a4d66753b18eaa37a1621246f660472243b001894f970037548d953b
license    : BSD-3-Clause
component  : programming.haskell
summary    : One module layer over regex-posix to replace Text.Regex
description: |
    One module layer over regex-posix to replace Text.Regex
builddeps  :
    - ghc
    - haskell-cabal-install
    - haskell-regex-posix
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
